---

- name: Ensure the asciinema install directory exists
  file:
    path: "{{ asciinema_install_dir }}"
    state: directory

- name: Ensure the azure-cli bin directory exists
  file:
    path: "{{ asciinema_bin_dir }}"
    state: directory
  when: asciinema_install_venv_helper is defined
        and asciinema_install_venv_helper

- name: Ensure Python 3 interpreter is used by Ansible
  set_fact:
    ansible_python_interpreter: "{{ asciinema_python3_path }}"

- name: Ensure asciinema is installed in a virtual environment
  pip:
    name: "{{ item }}"
    version: "{{ asciinema_version }}"
    state: present
    virtualenv: "{{ asciinema_install_dir }}/asciinema-{{ asciinema_version }}"
    virtualenv_command: "{{ asciinema_python3_path }} -m venv"
    virtualenv_site_packages: "{{ asciinema_venv_site_packages | default(False) }}"
  loop:
    - asciinema

- name: Ensure the originally configured Python interpreter is used by Ansible
  set_fact:
    ansible_python_interpreter: "{{ asciinema_ansible_python_interpreter }}"
  when: asciinema_ansible_python_interpreter is defined

- name: Ensure the current release is symlinked in the install directory
  file:
    src: "{{ asciinema_install_dir }}/asciinema-{{ asciinema_version }}"
    dest: "{{ asciinema_install_dir }}/{{ asciinema_current_dirname }}"
    state: link

- name: Ensure venv wrapper exists in virtualenv bin directory
  template:
    src: venv.sh.j2
    dest: "{{ asciinema_install_dir }}/asciinema-{{ asciinema_version }}/bin/venv"
    mode: 0755
  loop:
    - python

- name: Ensure venv helper exists for executables in bin directory
  template:
    src: venv.sh.j2
    dest: "{{ asciinema_bin_dir }}/{{ item }}"
    mode: 0755
  loop:
    - asciinema
  when: asciinema_install_venv_helper is defined
        and asciinema_install_venv_helper
