---

- import_tasks: pre-checks-os.yml

- include_tasks: "{{ ansible_os_family | lower }}/install-os-dependencies.yml"
  when: asciinema_install_os_dependencies is defined
        and asciinema_install_os_dependencies

- import_tasks: pre-checks-environment.yml

- import_tasks: get-version.yml
  when: asciinema_version is not defined
        or not asciinema_version

- import_tasks: install-asciinema.yml

- import_tasks: post-checks-environment.yml
