---

- name: Check to see if the asciinema version directory exists
  stat:
    path: "{{ asciinema_install_dir }}/asciinema-{{ asciinema_version }}"
  register: asciinema_check_version_dir

- name: Fail if the asciinema version directory doesn't exist
  fail:
    msg: "{{ asciinema_install_dir }}/asciinema-{{ asciinema_version }} is missing after play."
  when: not asciinema_check_version_dir.stat.exists

- name: Check to see if the asciinema current symlink exists
  stat:
    path: "{{ asciinema_install_dir }}/{{ asciinema_current_dirname }}"
  register: asciinema_check_symlink_dir

- name: Fail if the asciinema symlink directory doesn't exist
  fail:
    msg: "{{ asciinema_install_dir }}/{{ asciinema_current_dirname }} symlink not correct after play."
  when: not asciinema_check_symlink_dir.stat.exists
        or not asciinema_check_symlink_dir.stat.islnk
        or asciinema_check_symlink_dir.stat.lnk_target != (asciinema_install_dir + "/asciinema-" + asciinema_version)

- name: Check to see if the asciinema version directory is a virtualenv
  stat:
    path: "{{ asciinema_install_dir }}/{{ asciinema_current_dirname }}/bin/activate"
  register: asciinema_check_virtualenv_dir

- name: Fail if the asciinema virtualenv directory doesn't exist
  fail:
    msg: "{{ asciinema_install_dir }}/{{ asciinema_current_dirname }}/bin/activate not found after play."
  when: not asciinema_check_virtualenv_dir.stat.exists
        or not asciinema_check_virtualenv_dir.stat.isreg
